// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_Double_Window *w;
  Fl_Scroll *scrollArea1;
  Fl_Text_Display *textArea1;
  Fl_Button *btnStop1;
  Fl_Button *btnStart1;
  Fl_Scroll *scrollArea2;
  Fl_Text_Display *textArea2;
  Fl_Button *btnStop2;
  Fl_Button *btnStart2;
};
#endif
