// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "window.h"

UserInterface::UserInterface() {
  { w = new Fl_Double_Window(510, 330, "Thread Demo");
    w->user_data((void*)(this));
    { scrollArea1 = new Fl_Scroll(45, 37, 175, 215);
      scrollArea1->type(2);
      { textArea1 = new Fl_Text_Display(45, 37, 175, 215);
      } // Fl_Text_Display* textArea1
      scrollArea1->end();
    } // Fl_Scroll* scrollArea1
    { btnStop1 = new Fl_Button(150, 265, 70, 20, "Stop");
    } // Fl_Button* btnStop1
    { btnStart1 = new Fl_Button(45, 265, 70, 20, "Start");
    } // Fl_Button* btnStart1
    { scrollArea2 = new Fl_Scroll(280, 37, 175, 215);
      scrollArea2->type(2);
      { textArea2 = new Fl_Text_Display(280, 37, 175, 215);
      } // Fl_Text_Display* textArea2
      scrollArea2->end();
    } // Fl_Scroll* scrollArea2
    { btnStop2 = new Fl_Button(385, 265, 70, 20, "Stop");
    } // Fl_Button* btnStop2
    { btnStart2 = new Fl_Button(280, 265, 70, 20, "Start");
    } // Fl_Button* btnStart2
    { new Fl_Box(65, 18, 135, 23, "Thread 1");
    } // Fl_Box* o
    { new Fl_Box(300, 18, 135, 23, "Thread 2");
    } // Fl_Box* o
    w->end();
  } // Fl_Double_Window* w
}
