// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "window.h"

UserInterface::UserInterface() {
  { w = new Fl_Double_Window(385, 305, "AddSub");
    w->box(FL_EMBOSSED_BOX);
    w->user_data((void*)(this));
    { inputValue1 = new Fl_Int_Input(59, 51, 128, 41, "A");
      inputValue1->type(2);
      inputValue1->labelsize(20);
      inputValue1->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Int_Input* inputValue1
    { btnSub = new Fl_Button(197, 100, 128, 40, "A-B");
    } // Fl_Button* btnSub
    { inputValue2 = new Fl_Int_Input(197, 51, 128, 41, "B");
      inputValue2->type(2);
      inputValue2->labelsize(20);
      inputValue2->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Int_Input* inputValue2
    { boxResult = new Fl_Box(60, 150, 265, 67);
      boxResult->box(FL_DOWN_BOX);
      boxResult->labelsize(28);
    } // Fl_Box* boxResult
    { btnAdd = new Fl_Button(59, 100, 128, 41, "A+B");
    } // Fl_Button* btnAdd
    { btnClear = new Fl_Button(60, 226, 265, 40, "Clear");
    } // Fl_Button* btnClear
    w->end();
  } // Fl_Double_Window* w
}
