// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_Double_Window *w;
  Fl_Int_Input *inputValue1;
  Fl_Button *btnSub;
  Fl_Int_Input *inputValue2;
  Fl_Box *boxResult;
  Fl_Button *btnAdd;
  Fl_Button *btnClear;
};
#endif
