// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>

class UserInterface {
public:
  UserInterface();
  Fl_Double_Window *w;
protected:
  Fl_Input *inputValue;
  Fl_Button *readButton;
};
#endif
