// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "window.h"

UserInterface::UserInterface() {
  { w = new Fl_Double_Window(295, 70, "Read Value");
    w->user_data((void*)(this));
    { inputValue = new Fl_Input(75, 23, 95, 24, "Value");
    } // Fl_Input* inputValue
    { readButton = new Fl_Button(180, 22, 65, 25, "Read");
    } // Fl_Button* readButton
    w->end();
  } // Fl_Double_Window* w
}
