// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "window.h"

UserInterface::UserInterface() {
  { w = new Fl_Double_Window(520, 490, "Simple CRUD");
    w->user_data((void*)(this));
    { inputName = new Fl_Input(80, 48, 360, 24, "Name");
    } // Fl_Input* inputName
    { inputType = new Fl_Input(80, 73, 360, 24, "Type");
    } // Fl_Input* inputType
    { btnClear = new Fl_Button(24, 122, 100, 25, "Clear");
    } // Fl_Button* btnClear
    { btnUpdate = new Fl_Button(147, 122, 100, 25, "Update");
    } // Fl_Button* btnUpdate
    { btnDelete = new Fl_Button(270, 122, 100, 25, "Delete");
    } // Fl_Button* btnDelete
    { btnInsert = new Fl_Button(394, 122, 100, 25, "Insert");
    } // Fl_Button* btnInsert
    { Fl_Box* o = new Fl_Box(132, 16, 255, 16, "Simple CRUD");
      o->labelfont(1);
      o->labelsize(22);
    } // Fl_Box* o
    { browser = new Fl_Browser(24, 169, 470, 277);
      browser->type(2);
    } // Fl_Browser* browser
    w->end();
  } // Fl_Double_Window* w
}
